[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = 'contracts/test'
cache_path = 'contracts/cache'
optimizer = true
optimizer-runs = 1_000

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
opgoerli = "${OPGOERLI_RPC_URL}"
degen = "${DEGEN_RPC_URL}"
