[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = 'contracts/test'
broadcast = 'contracts/broadcast'
cache_path = 'contracts/cache'
optimizer = true
optimizer-runs = 1_000

[rpc_endpoints]
degen = "${DEGEN_RPC_URL}"
opsepolia = "${OPSEPOLIA_RPC_URL}"
