[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
broadcast = 'broadcast'
cache_path = 'cache'
optimizer = true
optimizer-runs = 1_000

[rpc_endpoints]
degen = "${DEGEN_RPC_URL}"
